services:
  fastapi-app:
    build: ./src/backend
    container_name: fastapi-container
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file: 
      - .env
    volumes:
      - ./src/backend/markdown:/app/markdown
    develop:
      watch:
        - action: sync
          path: ./src/backend/src
          target: /app
  vite-app:
    image: node:20
    container_name: vite-app
    volumes:
      - ./src/app:/app
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:8080"
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
    develop:
      watch:
        - action: sync
          path: ./src/app
          target: /app
    depends_on:
      - db

  db:
    image: mariadb:lts
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MARIADB_DATABASE: ${DATABASE_NAME}
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      # PMA_PORT: 3306
      # MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db-data:
